jobs:
  include:
  
  - stage: Arduino
    name: "Arduino"
    
    language: python
    python:
      - "3.9"

    cache:
      directories:
        - "~/.platformio"

    env:
      - PLATFORMIO_CI_SRC=Hexapod-master/Hexapod_Arduino


    install:
      - pip install -U platformio

    script:
      - platformio run -d $PLATFORMIO_CI_SRC
      
    
#    Qt doesn't work because armv7docker image couldn't be found
      
  - stage: Qt
    name: "Qt"
    
    language: python
    python:
      - "3.9"
      - "3.9-dev"  # 3.9 development branch
      - "nightly"  # nightly build
    # command to install dependencies
    install:
      - pip install -r Hexapod-master/Hexapod_Qt/pip_requirements.txt
    # command to run tests
    script:
      - Hexapod-master/Hexapod_Qt/MANUS_QT.py
