language: python
python:
  - "3.9"

cache:
  directories:
    - "~/.platformio"

env:
  - PLATFORMIO_CI_SRC=Hexapod-master/Hexapod_Arduino/src/main.cpp

install:
  - pip install -U platformio

script:
  - platformio ci --project-conf= Hexapod-master/Hexapod_Arduino/platformio.ini
