

name:"Arduino test"
language: python
python:
  - "3.6"
  
cache:
  directories:
    - "~/.platformio"

env:
  - PLATFORMIO_CI_SRC=Hexapod-master/Hexapod_Arduino


install:
  - pip install -U platformio

script:
  - platformio run -d $PLATFORMIO_CI_SRC
