jobs:
  include:
  
  - stage: Arduino
    name: "Arduino"
    
    language: python
    python:
      - "3.9"

    cache:
      directories:
        - "~/.platformio"

    env:
      - PLATFORMIO_CI_SRC=Hexapod-master/Hexapod_Arduino


    install:
      - pip install -U platformio

    script:
      - platformio run -d $PLATFORMIO_CI_SRC
      
  - stage: Qt
    name: "Qt"
    
    arch:
    - arm64
    
    sudo: required
    
    env:
    - IMGNAME=sedden/rpi-raspbian-qemu:wheezy

    services:
      - docker

    before_script:
      - docker image build -t ${IMGNAME} .

    script:
      - docker build -t Qt/test Qt
      - docker run -it Qt/test uname -a
      - docker run -it Qt/test make check
