language: python
python:
  - "3.9"

cache:
  directories:
    - "~/.platformio"

env:
  - PLATFORMIO_CI_SRC=src/main.cpp

install:
  - pip install -U platformio

script:
  - platformio ci --board=TYPE_1 --board=TYPE_2 --board=TYPE_N
