language: python
python:
  - "2.7"
  
cache:
  directories:
    - "~/.platformio"

env:
  - PLATFORMIO_CI_SRC=Hexapod-master/Hexapod_Arduino


install:
  - pip install -U platformio

script:
  - platformio ci --board=TYPE_1 --board=TYPE_2 --board=TYPE_N
